default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DEVELOPMENT_DB_NAME'] %>


test:
  <<: *default
  database: <%= ENV['TEST_DB_NAME'] %>



production:
  <<: *default
  database: STING_production
  password: <%= ENV["STING_DATABASE_PASSWORD"] %>
